name: Rust

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: ssh_to
            archive: ssh_to-linux.tar.gz

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: ssh_to.exe
            archive: ssh_to-windows.zip

          - os: macos-latest
            target: x86_64-apple-darwin
            binary: ssh_to
            archive: ssh_to-macos.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --release --target ${{ matrix.target }}

      - name: Package binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          tar -czf ${{ matrix.archive }} \
          -C target/${{ matrix.target }}/release \
          ${{ matrix.binary }}

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive `
          -Path target/${{ matrix.target }}/release/${{ matrix.binary }} `
          -DestinationPath ${{ matrix.archive }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/ssh_to-linux.tar.gz/ssh_to-linux.tar.gz
            artifacts/ssh_to-windows.zip/ssh_to-windows.zip
            artifacts/ssh_to-macos.tar.gz/ssh_to-macos.tar.gz